<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
<!-- Generated by NotebookLM Corrected Mindmap Extractor v6.0 with X-Level Parent-Child Logic -->
  <node ID="node_0" TEXT="Beyond Oaths: A Found Family&apos;s Loyalty Against Corruption">
    <node ID="node_1" TEXT="Definition of Bond">
      <node ID="node_5" TEXT="Profound, Absolute Loyalty">
      </node>
      <node ID="node_6" TEXT="Core Trio: Kaelen, Garrett, Serafina">
      </node>
      <node ID="node_7" TEXT="Transcends Order Loyalty">
      </node>
      <node ID="node_8" TEXT="Found Family Dynamic">
      </node>
      <node ID="node_9" TEXT="Forged in Shared Isolation">
      </node>
      <node ID="node_10" TEXT="Cemented by Traumatic Experiences">
      </node>
    </node>
    <node ID="node_2" TEXT="Origins of the Bond">
      <node ID="node_11" TEXT="Incident at the Silent Spire">
      </node>
      <node ID="node_12" TEXT="Key Events">
        <node ID="node_24" TEXT="Ambushed by Stray">
        </node>
        <node ID="node_25" TEXT="Commander Killed">
        </node>
        <node ID="node_26" TEXT="Garrett Grievously Wounded">
        </node>
      </node>
      <node ID="node_13" TEXT="Trio&apos;s Actions">
        <node ID="node_27" TEXT="Kaelen: Dark Mode (Oathbringer) to Save Garrett">
        </node>
        <node ID="node_28" TEXT="Serafina: Healed Garrett, Trusted Kaelen as Shield">
        </node>
      </node>
      <node ID="node_14" TEXT="Solidified Roles">
        <node ID="node_29" TEXT="Kaelen: Reckless Protector">
        </node>
        <node ID="node_30" TEXT="Garrett: Vulnerable Sentinel">
        </node>
        <node ID="node_31" TEXT="Serafina: Compassionate Anchor">
        </node>
      </node>
      <node ID="node_15" TEXT="Seeds of Distrust">
        <node ID="node_32" TEXT="Order&apos;s Cover-up of Incident">
        </node>
        <node ID="node_33" TEXT="Kaelen&apos;s First Great Secret">
        </node>
        <node ID="node_34" TEXT="Oathbringer&apos;s &apos;Wrongness&apos;">
        </node>
        <node ID="node_35" TEXT="Resurfacing Battle vs. Shadow Self">
        </node>
      </node>
    </node>
    <node ID="node_3" TEXT="Fractured Loyalty to the Order">
      <node ID="node_16" TEXT="Kaelen">
        <node ID="node_36" TEXT="Initially Pure, Earnest, Absolute Loyalty">
        </node>
        <node ID="node_37" TEXT="Order as Salvation, Noble Cause">
        </node>
        <node ID="node_38" TEXT="Betrayal Devastating Blow to Identity">
        </node>
      </node>
      <node ID="node_17" TEXT="Garrett">
        <node ID="node_39" TEXT="Cynical about Order">
        </node>
        <node ID="node_40" TEXT="Sees Flawed, Hypocritical System">
        </node>
        <node ID="node_41" TEXT="Serves to Restore Family Name">
        </node>
        <node ID="node_42" TEXT="True Loyalty: Kaelen &amp; Serafina">
        </node>
        <node ID="node_43" TEXT="Will Defy Rules/Elders for Trio">
        </node>
        <node ID="node_44" TEXT="Grandfather&apos;s Disgrace (Mathis Alerion)">
        </node>
      </node>
      <node ID="node_18" TEXT="Serafina">
        <node ID="node_45" TEXT="Loyalty to Ideals of Order">
        </node>
        <node ID="node_46" TEXT="White Flame, Healing, Compassion, Protecting Innocent">
        </node>
        <node ID="node_47" TEXT="Defies Bureaucracy/Commands">
        </node>
        <node ID="node_48" TEXT="Prioritizes Saving Kaelen&apos;s Soul">
        </node>
      </node>
    </node>
    <node ID="node_4" TEXT="Impact on Confronting External Corruption">
      <node ID="node_19" TEXT="Shared Purpose &amp; Support">
        <node ID="node_49" TEXT="Confront Threats Together">
        </node>
        <node ID="node_50" TEXT="Serafina: Compassion, Spiritual Anchor">
        </node>
        <node ID="node_51" TEXT="Garrett: Pragmatism, Tactical Mind, Physical Protection">
        </node>
        <node ID="node_52" TEXT="Serafina Pulls Kaelen from Darkness (Inner Flame)">
        </node>
        <node ID="node_53" TEXT="Garrett: Protector, Tactical Shield-Brother">
        </node>
      </node>
      <node ID="node_20" TEXT="Internal vs. External Corruption">
        <node ID="node_54" TEXT="Kaelen&apos;s Internal Struggle (Shadow Self)">
        </node>
        <node ID="node_55" TEXT="Shadow Self Exploits Fears, Grief (Elara&apos;s Death)">
        </node>
        <node ID="node_56" TEXT="Promise to Protect Elara/Oakhaven (Vulnerability)">
        </node>
      </node>
      <node ID="node_21" TEXT="Resisting Manipulation">
        <node ID="node_57" TEXT="Strengthens Against Valerius&apos;s Manipulations">
        </node>
        <node ID="node_58" TEXT="Resists Whispering Winds">
        </node>
        <node ID="node_59" TEXT="Doctrine of Trust (Open Communication)">
        </node>
        <node ID="node_60" TEXT="Garrett &amp; Serafina Urge Kaelen to Communicate">
        </node>
      </node>
      <node ID="node_22" TEXT="Challenging the Status Quo">
        <node ID="node_61" TEXT="Defy Corrupted Order of White Flame">
        </node>
        <node ID="node_62" TEXT="Become Fugitives">
        </node>
        <node ID="node_63" TEXT="Hope for Kaelen: Isolated &amp; Radical Stance">
        </node>
        <node ID="node_64" TEXT="Uncovering Deep-Seated Secrets/Betrayals">
        </node>
        <node ID="node_65" TEXT="Mission Shifts: Uncover Oathbringer&apos;s Curse">
        </node>
        <node ID="node_66" TEXT="Seek Secret Outcome to Save Kaelen&apos;s Soul">
        </node>
      </node>
      <node ID="node_23" TEXT="Moral Ambiguity &amp; Choice">
        <node ID="node_67" TEXT="Kaelen&apos;s Temptation (Shadow Self&apos;s Power)">
        </node>
        <node ID="node_68" TEXT="What Constitutes &apos;True Strength&apos;?">
        </node>
        <node ID="node_69" TEXT="Victory &apos;No Matter the Cost&apos;?">
        </node>
        <node ID="node_70" TEXT="Pushes Difficult Choices">
        </node>
        <node ID="node_71" TEXT="Sacrificing Themselves/Defying Allegiances">
        </node>
      </node>
    </node>
  </node>
</map>