domain: INFRA
last_updated: '2026-05-19T15:21:38.899327'
skills:
- documented: true
  id: database-design
  path: /.agent/skills/infra/database-design
- documented: true
  id: deployment-procedures
  path: /.agent/skills/infra/deployment-procedures
- documented: true
  id: insforge
  path: /.agent/skills/infra/insforge
- documented: true
  id: insforge-cli
  path: /.agent/skills/infra/insforge-cli
- documented: true
  id: mcp-builder
  path: /.agent/skills/infra/mcp-builder
- documented: true
  id: server-management
  path: /.agent/skills/infra/server-management
