"""# TOOL-COOPER-001: The Barrel Generator (Sovereign Indexes).

## I. Universal Identification & Provenance (The Vector Signature)
| Field | Value |
| :--- | :--- |
| **Artifact ID** | `TOOL-COOPER-001` |
| **Official Name** | `generate_barrels.py` |
| **Version** | **v1.1** |
| **Role** | **Recursive Indexer** |
| **Ethos** | **Fractal Sovereignty** |

---

# Description
Traverses a directory tree and generates a `00_INDEX.md` (The Barrel) in each folder.
The Barrel summarizes:
1. Sub-Modules (Directories)
2. Artifacts (Files with descriptions)

"""

import argparse
import os
import sys

IGNORE_DIRS = {
    ".git",
    "node_modules",
    "__pycache__",
    ".vscode",
    ".agent",
    ".trunk",
    ".gemini",
    "venv",
    ".venv",
}
INDEX_FILENAME = "00_INDEX.md"


def parse_title(filepath: str) -> str:
    """Extracts the first H1 or returns filename."""
    try:
        with open(filepath, encoding="utf-8") as f:
            for line in f:
                if line.startswith("# "):
                    return line.strip("# ").strip()
    except Exception:
        pass
    return os.path.basename(filepath)


def generate_barrel_content(root: str, dirs: list[str], files: list[str]) -> str:
    """Generates the Markdown content for the Barrel."""
    dirname = os.path.basename(root)
    md = f"# Barrel: {dirname}\n\n"
    md += f"> **Path:** `{root}`\n\n"

    # Sub-Modules
    if dirs:
        md += "## 📂 Sub-Modules (Barrels)\n"
        md += "| Module | Index |\n| :--- | :--- |\n"
        for d in sorted(dirs):
            md += f"| **{d}/** | [Open Barrel ({d})]({d}/{INDEX_FILENAME}) |\n"
        md += "\n"

    # Artifacts
    md += "## 📄 Artifacts (Manifest)\n"
    md += "| File | Description |\n| :--- | :--- |\n"

    has_files = False
    for f in sorted(files):
        if f == INDEX_FILENAME:
            continue
        if f.endswith(".md"):
            title = parse_title(os.path.join(root, f))
            md += f"| [{f}]({f}) | {title} |\n"
            has_files = True
        elif f.endswith(".py") or f.endswith(".ts") or f.endswith(".json"):
            md += f"| [{f}]({f}) | Code Artifact |\n"
            has_files = True

    if not has_files:
        md += "| *None* | *Empty* |\n"

    md += "\n---\n*Generated by The Cooper (TOOL-COOPER-001)*"
    return md


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Index Barrels")
    parser.add_argument("target", help="Target directory (recursive)")
    args = parser.parse_args()

    target = os.path.abspath(args.target)
    sys.stdout.write(f"Indexing Barrels for: {target}\n")

    for root, dirs, files in os.walk(target):
        # Filter hidden/ignored dirs
        dirs[:] = [d for d in dirs if d not in IGNORE_DIRS and not d.startswith(".")]

        # Determine if we should generate a barrel here
        # We generate barrels for ALL visited directories
        content = generate_barrel_content(root, dirs, files)

        barrel_path = os.path.join(root, INDEX_FILENAME)
        with open(barrel_path, "w", encoding="utf-8") as f:
            f.write(content)

        sys.stdout.write(f"  + Barrel Forged: {barrel_path}\n")


if __name__ == "__main__":
    main()
