/**
 * # TOOL-TARO-001: The Tarot Geode (Archetype Registry)
 *
 * ## I. Universal Identification & Provenance
 * | Attribute | Value |
 * | :--- | :--- |
 * | **Artifact ID** | `TOOL-TARO-001` |
 * | **Official Name** | `Archetypes.ts` |
 * | **Version** | **v11.0** |
 * | **Domain** | `SYNR` |
 * | **Evolution** | **Archetypal Definition** |
 * | **Signal (ESF)** | `ESF-ALPHA` |
 * | **Status (State)** | `[ACTIVE]` |
 * | **Tier** | **Strategic** |
 * | **Celestial Class** | `[STAR]` |
 * | **Governance** | `GVRN-SYNERGY-001` |
 * | **Provenance** | `Genesis Stamp: 2026-01-24` |
 * | **Relations** | `LINK: UMB-RULES-001`, `LINK: AOP-AG-003` |
 *
 * ---
 *
 * # --- RPG FRAMEWORK INTEGRATION ---
 * # System Slot: Registry Class
 * # Synergy Set: The Tarot Forge
 * # Primary Stat Buff: Wisdom (+20)
 * # Passive Ability: The Deck (Defines Tools)
 * # Cognitive Load Cost: Low
 * # XP Award Value: 100 XP
 *
 * ---
 *
 * ## IV. Actionable Prompt Packet (APP)
 * | Command ID | Action | Impact |
 * | :--- | :--- | :--- |
 * | `CMD: LIST_ARCHETYPES` | Returns Tarot definitions. | Enumerates system capabilities. |
 */

import type { SynarcheCard } from './DeckConfig';

export const ARCHETYPES: SynarcheCard[] = [
    // --- XI. JUSTICE (THE AUDITOR) ---
    {
        id: 'TOOL-JUST-001',
        majorArcana: 'XI',
        name: 'THE AUDITOR',
        role: 'System Compliance',
        primaryDomain: 'GVRN',
        description: 'The Scales of Truth. Measures Coherence and Integrity.',
        tier: 'Star',
        statBuff: { type: 'Coherence', value: 20, mechanism: 'Automated Dissonance Scan' },
        passivePerk: { name: 'Sovereign Gaze', description: 'Detects Protocol Drift.' },
        resourceEconomics: { cognitiveLoad: 'Medium', notes: 'Requires full system scan.' },
        crafting: { xpValue: 100 },
        theme: 'balance',
        icon: '⚖️',
        unlockLevel: 1,
        grimoire: [
            {
                id: 'audit_1',
                label: 'INITIATE AUDIT',
                description: 'Run full coherence scan.',
                cliCommand: 'python axion-core/tools/coherence_scan.py',
            },
        ],
    },

    // --- I. THE MAGICIAN (INGESTION SUITE) ---
    {
        id: 'TOOL-MAGI-001',
        majorArcana: 'I',
        name: 'THE INGESTOR',
        role: 'Ingest Vault',
        primaryDomain: 'SYNR',
        description: 'The Catalyst of Entry. Transforms raw matter into digital resonance.',
        tier: 'Planet',
        statBuff: { type: 'Adaptability', value: 10, mechanism: 'Universal format ingestion' },
        passivePerk: { name: 'Matter-to-Data', description: 'Recursively scans directories.' },
        resourceEconomics: { cognitiveLoad: 'Low', notes: 'Automated entry point.' },
        crafting: { xpValue: 50 },
        theme: 'chaos',
        icon: '🪄',
        unlockLevel: 1,
        grimoire: [
            {
                id: 'magi_1',
                label: 'INGEST VAULT',
                description: 'Ingest raw files.',
                cliCommand: 'python axion-core/tools/ingest_vault.py',
            },
        ],
    },
    {
        id: 'TOOL-MAGI-002',
        majorArcana: 'I',
        name: 'THE SCROLL',
        role: 'Extract Docx',
        primaryDomain: 'SYNR',
        description: 'The Unveiling Scroll. Deciphers binary-locked wisdom.',
        tier: 'Moon',
        statBuff: { type: 'Adaptability', value: 5, mechanism: 'Proprietary format decoding' },
        passivePerk: { name: 'Rosetta Stone', description: 'Reads .docx files.' },
        resourceEconomics: { cognitiveLoad: 'Low', notes: 'Utility script.' },
        crafting: { xpValue: 25 },
        theme: 'chaos',
        icon: '📜',
        unlockLevel: 1,
        grimoire: [
            {
                id: 'magi_2',
                label: 'EXTRACT DOCX',
                description: 'Converts Word docs to Markdown.',
                cliCommand: 'python axion-core/tools/extract_docx_text.py',
            },
        ],
    },
    {
        id: 'TOOL-MAGI-003',
        majorArcana: 'I',
        name: 'THE ALCHEMIST',
        role: 'Markdown Normalizer',
        primaryDomain: 'ARCH',
        description: 'The Transmutation Circle. Enforces structure upon chaos.',
        tier: 'Moon',
        statBuff: { type: 'Coherence', value: 15, mechanism: 'Standardizes format' },
        passivePerk: { name: 'Equivalent Exchange', description: 'Fixes header spacing.' },
        resourceEconomics: { cognitiveLoad: 'Low', notes: 'Automated cleanup.' },
        crafting: { xpValue: 75 },
        theme: 'chaos',
        icon: '⚗️',
        unlockLevel: 1,
        grimoire: [
            {
                id: 'magi_3',
                label: 'TRANSMUTE',
                description: 'Normalize markdown syntax.',
                cliCommand: 'python axion-core/tools/normalize_markdown.py',
                requiresInput: true,
                inputPrompt: 'Enter target file or directory:',
            },
        ],
    },

    // --- II. THE HIGH PRIESTESS (HARMONY SUITE) ---
    {
        id: 'TOOL-HPRI-001',
        majorArcana: 'II',
        name: 'SILVER THREAD',
        role: 'Graph Integrity',
        primaryDomain: 'SYNG',
        description: 'The Spirit Web. Detects orphans and heals broken links.',
        tier: 'Star',
        statBuff: { type: 'Synergy', value: 20, mechanism: 'Graph Analysis' },
        passivePerk: { name: 'Spirit Web', description: 'Orphan Detection.' },
        resourceEconomics: { cognitiveLoad: 'Medium', notes: 'Scans full weave.' },
        crafting: { xpValue: 100 },
        theme: 'balance',
        icon: '🕸️',
        unlockLevel: 2,
        grimoire: [
            {
                id: 'hpri_1',
                label: 'SCAN WEAVE',
                description: 'Analyze link graph.',
                cliCommand: 'python axion-core/tools/silver_thread.py',
                requiresInput: true,
                inputPrompt: 'Enter target directory:',
            },
        ],
    },
    {
        id: 'TOOL-HPRI-002',
        majorArcana: 'II',
        name: 'CONTEXT WEAVE',
        role: 'Cognitive Loom',
        primaryDomain: 'SYNG',
        description: 'The Loom of Fate. Weaves raw text into meaning.',
        tier: 'Star',
        statBuff: { type: 'Wisdom', value: 25, mechanism: 'Keyword Extraction' },
        passivePerk: { name: 'Pattern Recognition', description: 'Theme Analysis.' },
        resourceEconomics: { cognitiveLoad: 'High', notes: 'Deep synthesis.' },
        crafting: { xpValue: 150 },
        theme: 'balance',
        icon: '🧵',
        unlockLevel: 2,
        grimoire: [
            {
                id: 'hpri_2',
                label: 'WEAVE CONTEXT',
                description: 'Extract key themes.',
                cliCommand: 'python axion-core/tools/context_weave.py',
                requiresInput: true,
                inputPrompt: 'Enter text file path:',
            },
        ],
    },
    {
        id: 'TOOL-HPRI-002',
        majorArcana: 'II',
        name: 'THE ORACLE',
        role: 'Sophia Wisdom',
        primaryDomain: 'PHL',
        description: "The Oracle's Gaze. Injects philosophical depth into the mundane.",
        tier: 'Star',
        statBuff: { type: 'Creativity', value: 20, mechanism: 'Concept elevation' },
        passivePerk: { name: 'Epistemology', description: 'Raises artifact integrity.' },
        resourceEconomics: { cognitiveLoad: 'High', notes: 'Requires deep context.' },
        crafting: { xpValue: 150 },
        theme: 'void',
        icon: '🔮',
        unlockLevel: 10,
        grimoire: [
            {
                id: 'hpri_2',
                label: 'CONSULT SOPHIA',
                description: 'Injects wisdom markers.',
                cliCommand: 'python axion-core/tools/sophia_wisdom.py',
            },
        ],
    },
    {
        id: 'TOOL-HPRI-003',
        majorArcana: 'II',
        name: 'AKASHIC RECORD',
        role: 'Gen Registry',
        primaryDomain: 'ARCH',
        description: 'The Master Index of all created things.',
        tier: 'Planet',
        statBuff: { type: 'Coherence', value: 10, mechanism: 'Centralized indexing' },
        passivePerk: { name: 'Omniscience', description: 'Tracks all artifact IDs.' },
        resourceEconomics: { cognitiveLoad: 'Low', notes: 'Automated cron.' },
        crafting: { xpValue: 75 },
        theme: 'structure',
        icon: '📚',
        unlockLevel: 5,
        grimoire: [
            {
                id: 'hpri_3',
                label: 'UPDATE REGISTRY',
                description: 'Regenerates the Master Registry.',
                cliCommand: 'python axion-core/tools/generate_registry.py',
            },
        ],
    },
    {
        id: 'TOOL-HPRI-004',
        majorArcana: 'II',
        name: 'SEER LANTERN',
        role: 'Find Unlinked',
        primaryDomain: 'SYNG',
        description: 'Illuminates the lost and forgotten nodes.',
        tier: 'Moon',
        statBuff: { type: 'Synergy', value: 5, mechanism: 'Gap detection' },
        passivePerk: { name: 'Lost & Found', description: 'Identifies orphans.' },
        resourceEconomics: { cognitiveLoad: 'Low', notes: 'Maintenance tool.' },
        crafting: { xpValue: 30 },
        theme: 'void',
        icon: '🕯️',
        unlockLevel: 3,
        grimoire: [
            {
                id: 'hpri_4',
                label: 'FIND ORPHANS',
                description: 'Lists unlinked artifacts.',
                cliCommand: 'python axion-core/tools/find_unlinked.py',
            },
        ],
    },
    {
        id: 'TOOL-HPRI-005',
        majorArcana: 'II',
        name: 'TUNING FORK',
        role: 'Resonance Scan',
        primaryDomain: 'SYNG',
        description: 'Harmonises the frequency of the workspace.',
        tier: 'Planet',
        statBuff: { type: 'Synergy', value: 8, mechanism: 'Vibrational analysis' },
        passivePerk: { name: 'Harmony', description: 'Detects dissonance.' },
        resourceEconomics: { cognitiveLoad: 'Medium', notes: 'Diagnostic.' },
        crafting: { xpValue: 60 },
        theme: 'balance',
        icon: '🎼',
        unlockLevel: 7,
        grimoire: [
            {
                id: 'hpri_5',
                label: 'SCAN RESONANCE',
                description: 'Checks synergy levels.',
                cliCommand: 'python axion-core/tools/resonance_scanner.py',
            },
        ],
    },
    {
        id: 'TOOL-HPRI-006',
        majorArcana: 'II',
        name: 'THE LOOM',
        role: 'Catalyst Weave',
        primaryDomain: 'CRTV',
        description: 'The Loom of Potential. Weaves context for generation.',
        tier: 'Star',
        statBuff: { type: 'Creativity', value: 25, mechanism: 'Context synthesis' },
        passivePerk: { name: 'Creation', description: 'Prepares the canvas.' },
        resourceEconomics: { cognitiveLoad: 'High', notes: 'Core creative engine.' },
        crafting: { xpValue: 200 },
        theme: 'chaos',
        icon: '🧵',
        unlockLevel: 15,
        grimoire: [
            {
                id: 'hpri_6',
                label: 'WEAVE CONTEXT',
                description: 'Bundles context for AI.',
                cliCommand: 'python axion-core/tools/catalyst_weaver.py',
            },
        ],
    },

    // --- XVIII. THE MOON (COGNITION SUITE) ---
    {
        id: 'TOOL-LOOM-001',
        majorArcana: 'XVIII',
        name: 'CONTEXT WEAVE',
        role: 'Context Engine',
        primaryDomain: 'GVRN',
        description: 'The Loom of Meaning. Weaves dynamic context graphs.',
        tier: 'Moon',
        statBuff: { type: 'Insight', value: 25, mechanism: 'Relational mapping' },
        passivePerk: { name: 'Illusion', description: 'Visualizes hidden links.' },
        resourceEconomics: { cognitiveLoad: 'High', notes: 'Visualizer.' },
        crafting: { xpValue: 150 },
        theme: 'void',
        icon: '🕸️',
        unlockLevel: 10,
        grimoire: [
            {
                id: 'loom_1',
                label: 'WEAVE',
                description: 'Weaves context.',
                cliCommand: 'python axion-core/tools/context_weave.py',
            },
        ],
    },

    // --- IV. THE EMPEROR (SCHEMA SUITE) ---
    {
        id: 'TOOL-EMPR-001',
        majorArcana: 'IV',
        name: 'IMPERIAL DECREE',
        role: 'Reforge Lib',
        primaryDomain: 'GVRN',
        description: 'The Law of the Library. Enforces folder structure.',
        tier: 'Planet',
        statBuff: { type: 'Coherence', value: 12, mechanism: 'Structural enforcement' },
        passivePerk: { name: 'Order', description: 'Moves files to their homes.' },
        resourceEconomics: { cognitiveLoad: 'Medium', notes: 'Destructive.' },
        crafting: { xpValue: 100 },
        theme: 'structure',
        icon: '🏰',
        unlockLevel: 10,
        grimoire: [
            {
                id: 'empr_1',
                label: 'REFORGE LIBRARY',
                description: 'Organizes file system.',
                cliCommand: 'python axion-core/tools/reforge_library.py',
            },
        ],
    },
    {
        id: 'TOOL-EMPR-002',
        majorArcana: 'IV',
        name: 'THE GAVEL',
        role: 'Standardize',
        primaryDomain: 'GVRN',
        description: "The Architect's Gavel. Standardizes headers and metadata.",
        tier: 'Star',
        statBuff: { type: 'Coherence', value: 20, mechanism: 'Metadata standardization' },
        passivePerk: { name: 'UIP Injection', description: 'Ensures Universal Provenance.' },
        resourceEconomics: { cognitiveLoad: 'High', notes: 'Wide impact.' },
        crafting: { xpValue: 150 },
        theme: 'structure',
        icon: '⚖️',
        unlockLevel: 12,
        grimoire: [
            {
                id: 'empr_2',
                label: 'STANDARDIZE',
                description: 'Applies OGLN standards.',
                cliCommand: 'python axion-core/tools/standardize_docs.py',
            },
        ],
    },
    {
        id: 'TOOL-EMPR-003',
        majorArcana: 'IV',
        name: 'FOUNDATION',
        role: 'Scaffold Eng',
        primaryDomain: 'ARCH',
        description: 'The Foundation Stone. Scaffolds new projects.',
        tier: 'Planet',
        statBuff: { type: 'Adaptability', value: 10, mechanism: 'Quick start' },
        passivePerk: { name: 'Genesis', description: 'Rapid project creation.' },
        resourceEconomics: { cognitiveLoad: 'Low', notes: 'Setup tool.' },
        crafting: { xpValue: 50 },
        theme: 'structure',
        icon: '🏗️',
        unlockLevel: 2,
        grimoire: [
            {
                id: 'empr_3',
                label: 'SCAFFOLD',
                description: 'Generates engine boilerplate.',
                cliCommand: 'python axion-core/tools/scaffold_engine.py',
            },
        ],
    },
    {
        id: 'TOOL-EMPR-004',
        majorArcana: 'IV',
        name: 'THE STANDARD',
        role: 'RPG Header',
        primaryDomain: 'GVRN',
        description: 'The Imperial Standard. Injects RPG stats into files.',
        tier: 'Moon',
        statBuff: { type: 'Transparency', value: 5, mechanism: 'Gamification' },
        passivePerk: { name: 'Stats', description: 'Adds XP values.' },
        resourceEconomics: { cognitiveLoad: 'Low', notes: 'Metadata tool.' },
        crafting: { xpValue: 20 },
        theme: 'structure',
        icon: '🚩',
        unlockLevel: 3,
        grimoire: [
            {
                id: 'empr_4',
                label: 'APPLY HEADER',
                description: 'Injects RPG metadata.',
                cliCommand: 'python axion-core/tools/apply_rpg_header.py',
            },
        ],
    },

    // --- KnS. KNIGHT OF SWORDS (TRANSMUTATION SUITE) ---
    {
        id: 'TOOL-KNIG-001',
        majorArcana: 'KnS',
        name: 'REBIRTH BLADE',
        role: 'Reforge',
        primaryDomain: 'EVOL',
        description: 'The Blade of Rebirth. Aggressive code refactoring.',
        tier: 'Star',
        statBuff: { type: 'Adaptability', value: 18, mechanism: 'Code transformation' },
        passivePerk: { name: 'Transmute', description: 'Rewrites legacy code.' },
        resourceEconomics: { cognitiveLoad: 'High', notes: 'High risk, high reward.' },
        crafting: { xpValue: 250 },
        theme: 'destruction',
        icon: '⚔️',
        unlockLevel: 20,
        grimoire: [
            {
                id: 'knig_1',
                label: 'REFORGE CODE',
                description: 'Aggressively refactors file.',
                cliCommand: 'python axion-core/tools/reforge.py',
            },
        ],
    },
    {
        id: 'TOOL-KNIG-002',
        majorArcana: 'KnS',
        name: 'HONED EDGE',
        role: 'Knight Fixer',
        primaryDomain: 'EVOL',
        description: 'The precision scalpel for specific bugs.',
        tier: 'Planet',
        statBuff: { type: 'Coherence', value: 10, mechanism: 'Targeted fixing' },
        passivePerk: { name: 'Snipe', description: 'Fixes specific lints.' },
        resourceEconomics: { cognitiveLoad: 'Medium', notes: 'Surgical.' },
        crafting: { xpValue: 100 },
        theme: 'destruction',
        icon: '🗡️',
        unlockLevel: 15,
        grimoire: [
            {
                id: 'knig_2',
                label: 'FIX ISSUE',
                description: 'Runs targeted fix.',
                cliCommand: 'python axion-core/tools/knight_fixer.py',
            },
        ],
    },
    {
        id: 'TOOL-KNIG-003',
        majorArcana: 'KnS',
        name: 'PLATE ARMOR',
        role: 'Apply Std',
        primaryDomain: 'GVRN',
        description: 'The Plate of Order. Enforces coding standards.',
        tier: 'Planet',
        statBuff: { type: 'Coherence', value: 12, mechanism: 'Formatter' },
        passivePerk: { name: 'Discipline', description: 'Auto-formats code.' },
        resourceEconomics: { cognitiveLoad: 'Low', notes: 'Routine maintenance.' },
        crafting: { xpValue: 50 },
        theme: 'structure',
        icon: '🛡️',
        unlockLevel: 10,
        grimoire: [
            {
                id: 'knig_3',
                label: 'APPLY STANDARD',
                description: 'Formats code.',
                cliCommand: 'python axion-core/tools/apply_standard.py',
            },
        ],
    },
    {
        id: 'TOOL-KNIG-004',
        majorArcana: 'KnS',
        name: 'ALCHEMIST PATH',
        role: 'Transmutation',
        primaryDomain: 'EVOL',
        description: 'The Full Pipeline. From lead to gold.',
        tier: 'Nebula',
        statBuff: { type: 'Creativity', value: 25, mechanism: 'Full system pivot' },
        passivePerk: { name: 'Great Work', description: 'Transforms entire modules.' },
        resourceEconomics: { cognitiveLoad: 'Extreme', notes: 'Systemic change.' },
        crafting: { xpValue: 500 },
        theme: 'destruction',
        icon: '⚗️',
        unlockLevel: 25,
        grimoire: [
            {
                id: 'knig_4',
                label: 'TRANSMUTE',
                description: 'Runs full pipeline.',
                cliCommand: 'python axion-core/tools/transmutation_pipeline.py',
            },
        ],
    },

    // --- XVII. THE STAR (COHERENCE SUITE) ---
    {
        id: 'TOOL-STAR-001',
        majorArcana: 'XVII',
        name: 'CONSTELLATION',
        role: 'Test Weaver',
        primaryDomain: 'TECH',
        description: 'The Constellation Map. Weaves test coverage.',
        tier: 'Planet',
        statBuff: { type: 'Coherence', value: 15, mechanism: 'Test generation' },
        passivePerk: { name: 'Safety Net', description: 'Generates unit tests.' },
        resourceEconomics: { cognitiveLoad: 'Medium', notes: 'Verification.' },
        crafting: { xpValue: 100 },
        theme: 'balance',
        icon: '⭐',
        unlockLevel: 10,
        grimoire: [
            {
                id: 'star_1',
                label: 'WEAVE TESTS',
                description: 'Generates tests.',
                cliCommand: 'python axion-core/tools/test_weaver.py',
            },
        ],
    },
    {
        id: 'TOOL-STAR-002',
        majorArcana: 'XVII',
        name: 'ETERNAL JOURNAL',
        role: 'Chronicler',
        primaryDomain: 'ARCH',
        description: 'The Keeper of Time. Logs all system events.',
        tier: 'Star',
        statBuff: { type: 'Transparency', value: 20, mechanism: 'Immutable logging' },
        passivePerk: { name: 'Memory', description: 'Never forgets.' },
        resourceEconomics: { cognitiveLoad: 'Low', notes: 'Always running.' },
        crafting: { xpValue: 50 },
        theme: 'structure',
        icon: '📖',
        unlockLevel: 1,
        grimoire: [
            {
                id: 'star_2',
                label: 'CHRONICLE',
                description: 'Logs event.',
                cliCommand: 'python axion-core/tools/chronicle_manager.py',
            },
        ],
    },
    {
        id: 'TOOL-STAR-003',
        majorArcana: 'XVII',
        name: 'MILESTONE',
        role: 'Log Refactor',
        primaryDomain: 'EVOL',
        description: 'The Beacon. Marks major evolutionary steps.',
        tier: 'Moon',
        statBuff: { type: 'Transparency', value: 10, mechanism: 'Version tracking' },
        passivePerk: { name: 'Checkpoint', description: 'Saves state.' },
        resourceEconomics: { cognitiveLoad: 'Low', notes: 'Release management.' },
        crafting: { xpValue: 75 },
        theme: 'balance',
        icon: '🗿',
        unlockLevel: 5,
        grimoire: [
            {
                id: 'star_3',
                label: 'LOG MILESTONE',
                description: 'Records refactor.',
                cliCommand: 'python axion-core/tools/log_refactor_milestone.py',
            },
        ],
    },
    {
        id: 'TOOL-STAR-004',
        majorArcana: 'XVII',
        name: 'ASTRAL COMPASS',
        role: 'RAG Graph',
        primaryDomain: 'SYNR',
        description: 'The Map of Meaning. Generates the knowledge graph.',
        tier: 'Nebula',
        statBuff: { type: 'Synergy', value: 30, mechanism: 'Graph generation' },
        passivePerk: { name: 'Navigation', description: 'Connects all dots.' },
        resourceEconomics: { cognitiveLoad: 'High', notes: 'Heavy compute.' },
        crafting: { xpValue: 300 },
        theme: 'balance',
        icon: '🧭',
        unlockLevel: 20,
        grimoire: [
            {
                id: 'star_4',
                label: 'GENERATE GRAPH',
                description: 'Builds RAG graph.',
                cliCommand: 'python axion-core/tools/generate_rag_graph.py',
            },
        ],
    },
    {
        id: 'TOOL-CRYS-001',
        majorArcana: 'XVII',
        name: 'CRYSTALLINE',
        role: 'Cognition Focus',
        primaryDomain: 'GVRN',
        description: 'The Diamond Prism. Refracts problems into facets.',
        tier: 'Planet',
        statBuff: { type: 'Insight', value: 20, mechanism: '5-Why Analysis' },
        passivePerk: { name: 'Refraction', description: 'Splits complexity.' },
        resourceEconomics: { cognitiveLoad: 'Medium', notes: 'Analysis tool.' },
        crafting: { xpValue: 100 },
        theme: 'structure',
        icon: '💎',
        unlockLevel: 15,
        grimoire: [
            {
                id: 'crys_1',
                label: 'REFRACT',
                description: 'Analyze facets.',
                cliCommand: 'python axion-core/tools/refract_problem.py',
            },
        ],
    },

    // --- KiP. KING OF PENTACLES (ARCHIVAL SUITE) ---
    {
        id: 'TOOL-KING-001',
        majorArcana: 'KiP',
        name: 'ROYAL LEDGER',
        role: 'Map Markdown',
        primaryDomain: 'ARCH',
        description: 'The Structural Map of the kingdom.',
        tier: 'Planet',
        statBuff: { type: 'Transparency', value: 12, mechanism: 'Structure mapping' },
        passivePerk: { name: 'Cartography', description: 'Visualizes hierarchy.' },
        resourceEconomics: { cognitiveLoad: 'Low', notes: 'Reporting.' },
        crafting: { xpValue: 50 },
        theme: 'structure',
        icon: '🗺️',
        unlockLevel: 8,
        grimoire: [
            {
                id: 'king_1',
                label: 'MAP STRUCTURE',
                description: 'Maps folders.',
                cliCommand: 'python axion-core/tools/map_markdown_structure.py',
            },
        ],
    },
    {
        id: 'TOOL-KING-002',
        majorArcana: 'KiP',
        name: 'SOVEREIGN SEAL',
        role: 'Gen PRS',
        primaryDomain: 'GVRN',
        description: 'The Phoenix Rosetta Stone. The ultimate reference.',
        tier: 'Star',
        statBuff: { type: 'Coherence', value: 25, mechanism: 'Master Doc Generation' },
        passivePerk: { name: 'Edict', description: 'Defines reality.' },
        resourceEconomics: { cognitiveLoad: 'High', notes: 'Source of Truth.' },
        crafting: { xpValue: 200 },
        theme: 'structure',
        icon: '👑',
        unlockLevel: 25,
        grimoire: [
            {
                id: 'king_2',
                label: 'GENERATE PRS',
                description: 'Builds Rosetta Stone.',
                cliCommand: 'node axion-core/tools/generate_prs.js',
            },
        ],
    },

    // --- XXI. THE SENTINEL (AUDIT SUITE) ---
    {
        id: 'TOOL-SENT-001',
        majorArcana: 'XXI',
        name: 'UNBLINKING EYE',
        role: 'Compliance',
        primaryDomain: 'GVRN',
        description: 'The Ultimate Judge. Audits against the OGLN.',
        tier: 'Nebula',
        statBuff: { type: 'Coherence', value: 30, mechanism: 'Full compliance verify' },
        passivePerk: { name: 'Judgment', description: 'Pass/Fail entire system.' },
        resourceEconomics: { cognitiveLoad: 'Extreme', notes: 'The Gatekeeper.' },
        crafting: { xpValue: 500 },
        theme: 'balance',
        icon: '👁️',
        unlockLevel: 30,
        grimoire: [
            {
                id: 'sent_1',
                label: 'AUDIT',
                description: 'Runs full compliance.',
                cliCommand: 'python axion-core/tools/compliance_audit.py',
            },
        ],
    },
    {
        id: 'TOOL-SENT-002',
        majorArcana: 'XXI',
        name: 'WATCHTOWER',
        role: 'IDE Sentinel',
        primaryDomain: 'TECH',
        description: 'The Vigil. Ensures IDE/Editor integrity.',
        tier: 'Planet',
        statBuff: { type: 'Coherence', value: 10, mechanism: 'Env checking' },
        passivePerk: { name: 'Sentry', description: 'Watches environment.' },
        resourceEconomics: { cognitiveLoad: 'Low', notes: 'Passive.' },
        crafting: { xpValue: 50 },
        theme: 'structure',
        icon: '🗼',
        unlockLevel: 5,
        grimoire: [
            {
                id: 'sent_2',
                label: 'CHECK IDE',
                description: 'Scans VSCode settings.',
                cliCommand: 'python axion-core/tools/ide_sentinel.py',
            },
        ],
    },
    {
        id: 'TOOL-SENT-003',
        majorArcana: 'XXI',
        name: 'DUST SIFTER',
        role: 'Lint Artifact',
        primaryDomain: 'GVRN',
        description: 'The Sifter. Details linting of single artifacts.',
        tier: 'Moon',
        statBuff: { type: 'Precision', value: 15, mechanism: 'Granular linting' },
        passivePerk: { name: 'Detail', description: 'Finds micro-errors.' },
        resourceEconomics: { cognitiveLoad: 'Low', notes: 'Targeted.' },
        crafting: { xpValue: 40 },
        theme: 'structure',
        icon: '🧹',
        unlockLevel: 3,
        grimoire: [
            {
                id: 'sent_3',
                label: 'LINT FILE',
                description: 'Lints a file.',
                cliCommand: 'python axion-core/tools/lint_artifact.py',
            },
        ],
    },
    {
        id: 'TOOL-SENT-004',
        majorArcana: 'XXI',
        name: 'JUDGE BENCH',
        role: 'Analyze Docs',
        primaryDomain: 'GVRN',
        description: 'The Bench. Deep analysis of documentation sets.',
        tier: 'Star',
        statBuff: { type: 'Insight', value: 20, mechanism: 'Corpus analysis' },
        passivePerk: { name: 'Verdict', description: 'Judges doc sets.' },
        resourceEconomics: { cognitiveLoad: 'Medium', notes: 'Reporting.' },
        crafting: { xpValue: 100 },
        theme: 'structure',
        icon: '🔨',
        unlockLevel: 15,
        grimoire: [
            {
                id: 'sent_4',
                label: 'ANALYZE DOCS',
                description: 'Analyzes folder.',
                cliCommand: 'python axion-core/tools/analyze_docs_compliance.py',
            },
        ],
    },
    {
        id: 'TOOL-SENT-005',
        majorArcana: 'XXI',
        name: 'WAYFINDER',
        role: 'Diag Paths',
        primaryDomain: 'TECH',
        description: 'The Compass. Debugs pathing issues.',
        tier: 'Moon',
        statBuff: { type: 'Precision', value: 10, mechanism: 'Path resolution' },
        passivePerk: { name: 'Direction', description: 'Fixes broken links.' },
        resourceEconomics: { cognitiveLoad: 'Low', notes: 'Utility.' },
        crafting: { xpValue: 30 },
        theme: 'balance',
        icon: '🛤️',
        unlockLevel: 2,
        grimoire: [
            {
                id: 'sent_5',
                label: 'DIAGNOSE',
                description: 'Checks paths.',
                cliCommand: 'python axion-core/tools/diagnose_paths.py',
            },
        ],
    },
    {
        id: 'TOOL-SENT-006',
        majorArcana: 'XXI',
        name: 'EXECUTIONER',
        role: 'Sentinel Sword',
        primaryDomain: 'GVRN',
        description: 'The Sword. Enforces styling with finality.',
        tier: 'Star',
        statBuff: { type: 'Coherence', value: 25, mechanism: 'Strict enforcement' },
        passivePerk: { name: 'Sever', description: 'Cuts deviation.' },
        resourceEconomics: { cognitiveLoad: 'High', notes: 'Destructive.' },
        crafting: { xpValue: 150 },
        theme: 'destruction',
        icon: '⚔️',
        unlockLevel: 20,
        grimoire: [
            {
                id: 'sent_6',
                label: 'SWING SWORD',
                description: 'Enforces style.',
                cliCommand: 'python axion-core/tools/sentinel_sword.py',
            },
        ],
    },
    {
        id: 'TOOL-SENT-007',
        majorArcana: 'XXI',
        name: 'RIPPLE TRACER',
        role: 'Impact Analysis',
        primaryDomain: 'TECH',
        description: 'The Tracer. Simulates impact of changes.',
        tier: 'Star',
        statBuff: { type: 'Insight', value: 20, mechanism: 'Dependency tracing' },
        passivePerk: { name: 'Foresight', description: 'Predicts breakage.' },
        resourceEconomics: { cognitiveLoad: 'Medium', notes: 'Pre-commit.' },
        crafting: { xpValue: 120 },
        theme: 'balance',
        icon: '📡',
        unlockLevel: 12,
        grimoire: [
            {
                id: 'sent_7',
                label: 'TRACE IMPACT',
                description: 'Checks dependencies.',
                cliCommand: 'python axion-core/tools/impact_analysis.py',
            },
        ],
    },
    {
        id: 'TOOL-SENT-008',
        majorArcana: 'XXI',
        name: 'GEOMETRIC TRUTH',
        role: 'Verify AST',
        primaryDomain: 'TECH',
        description: 'The Geometric Truth. Validates code structure.',
        tier: 'Planet',
        statBuff: { type: 'Precision', value: 15, mechanism: 'AST Parsing' },
        passivePerk: { name: 'Geometry', description: 'Checks syntax tree.' },
        resourceEconomics: { cognitiveLoad: 'Medium', notes: 'Validation.' },
        crafting: { xpValue: 80 },
        theme: 'structure',
        icon: '📐',
        unlockLevel: 10,
        grimoire: [
            {
                id: 'sent_8',
                label: 'VERIFY AST',
                description: 'Parses AST.',
                cliCommand: 'python axion-core/tools/verify_ast.py',
            },
        ],
    },
];

// Re-export ProtocolCommand for convenience
export type { ProtocolCommand } from './DeckConfig';

