/**
 * GENERATE_PRS.JS
 * ------------------------------------------------------------------
 * Role: The Automated Scribe
 * Function: Scrapes Markdown files for Phoenix Metadata and rebuilds
 * the PRS-001.json "Grimoire" from scratch.
 * ------------------------------------------------------------------
 */

const fs = require("node:fs");
const path = require("node:path");

// --- CONFIGURATION ---
const CONFIG = {
  rootDir: "./src", // The directory to scan (change to '.' for root)
  outputFile: "./PRS-001.json",
  allowedExtensions: [".md", ".txt"],
  // The "Soul" of the PRS - Static metadata that doesn't change often
  prsHeader: {
    artifact_id: "PRS-001",
    official_name: "The Phoenix Rosetta Stone",
    version: "5.0 (Live-Generated)",
    last_updated: new Date().toISOString(),
    governing_ethos: "Guardian of Truth",
    description:
      "The Master Navigational Hub and Knowledge Graph, auto-generated by the Transmutation Architect.",
  },
};

// --- REGEX PATTERNS (The Eyes) ---
// These patterns hunt for the specific "Phoenix Protocol" headers in your text.
const PATTERNS = {
  // Matches "**Artifact ID:** Value" or "Artifact ID: Value"
  id: /(?:(?:\*\*|#+\s*)?(?:Artifact ID|Module ID|Blueprint ID|Playbook ID|Command ID|Metric ID|Log ID)(?:\*\*)?):\s*(.*)/i,
  name: /(?:(?:\*\*|#+\s*)?(?:Official Name|Module Name|Blueprint Title|Playbook Title|Command Title|Metric Title|Log Title)(?:\*\*)?):\s*(.*)/i,
  type: /(?:(?:\*\*|#+\s*)?(?:Artifact Type|Type)(?:\*\*)?):\s*(.*)/i,
  domain:
    /(?:(?:\*\*|#+\s*)?(?:Primary Domain Alignment|Primary Domain|Domain)(?:\*\*)?):\s*(.*)/i,
  ethos: /(?:(?:\*\*|#+\s*)?(?:Governing Ethos)(?:\*\*)?):\s*(.*)/i,
  purpose:
    /(?:(?:\*\*|#+\s*)?(?:Core Purpose|Purpose|Objective|What \(.*\))(?:\*\*)?):\s*(.*)/i,
  tags: /(?:(?:\*\*|#+\s*)?(?:Semantic Tags|Tags)(?:\*\*)?):\s*(.*)/i,
};

// --- LOGIC CORE ---

function scanDirectory(directory) {
  let results = [];
  if (!fs.existsSync(directory)) {
    console.warn(`[WARNING] Directory not found: ${directory}`);
    return results;
  }

  const list = fs.readdirSync(directory);
  list.forEach((file) => {
    const fullPath = path.join(directory, file);
    const stat = fs.statSync(fullPath);

    if (stat && stat.isDirectory()) {
      // Recurse into subdirectories (The Deep Scan)
      results = results.concat(scanDirectory(fullPath));
    } else if (CONFIG.allowedExtensions.includes(path.extname(file))) {
      // Check extension
      results.push(fullPath);
    }
  });
  return results;
}

function cleanText(text) {
  if (!text) return "";
  // Remove leading/trailing markdown bold/italic/headers and invisible spaces
  return text.replace(/^[\s*#_]+|[\s*#_]+$/g, "").trim();
}

function extractMetadata(filePath) {
  const content = fs.readFileSync(filePath, "utf8");
  const filename = path.basename(filePath);

  // Default Node Object
  let node = {
    id: "UNKNOWN-" + filename, // Temporary fallback
    label: filename,
    type: "Artifact",
    definition: "No definition found.",
    tags: [],
    location: filePath.replace(/\\/g, "/"), // Ensure forward slashes for JSON
  };

  // 1. Extract ID (The Soul)
  const idMatch = PATTERNS.id.exec(content);
  if (idMatch) node.id = cleanText(idMatch[1]);

  // 2. Extract Name (The Identity)
  const nameMatch = PATTERNS.name.exec(content);
  if (nameMatch) node.label = cleanText(nameMatch[1]);

  // 3. Extract Type (The Caste)
  // Try explicit match first, then infer from ID
  const typeMatch = PATTERNS.type.exec(content);
  if (typeMatch) {
    node.type = cleanText(typeMatch[1]);
  } else if (node.id.startsWith("UMB")) node.type = "Blueprint";
  else if (node.id.startsWith("AOP")) node.type = "Protocol";
  else if (node.id.startsWith("GUCA")) node.type = "Command";
  else if (node.id.startsWith("SELT")) node.type = "Log";

  // 4. Extract Definition (The Purpose)
  const purpMatch = PATTERNS.purpose.exec(content);
  if (purpMatch) {
    // Clean up the string (remove leading bullets or "Summary:")
    let cleanDef = purpMatch[1].trim().replace(/^Summary:\s*/i, "");
    if (cleanDef.length > 300) cleanDef = cleanDef.substring(0, 297) + "..."; // Truncate
    node.definition = cleanText(cleanDef);
  }

  // 5. Extract Tags/Domain (The Alignment)
  const domainMatch = PATTERNS.domain.exec(content);
  if (domainMatch) node.tags.push(cleanText(domainMatch[1]));

  const tagsMatch = PATTERNS.tags.exec(content);
  if (tagsMatch) {
    // Split by comma or hash
    const rawTags = tagsMatch[1].split(/,|#/);
    rawTags.forEach((t) => {
      const clean = cleanText(t);
      if (clean && !node.tags.includes(clean)) node.tags.push(clean);
    });
  }

  // 6. Extract References (The Threads)
  // Looking for patterns like UMB-XXX-000, AOP-XXX-000, or specifically known Core IDs
  const idPattern =
    /(?:UMB|AOP|GUCA|SELT|DOC|gw)-[A-Z]{2,}-\d{3}|AISTF|OGLN|Synarche|Phoenix_Cycle|ContextWeave/g;
  const foundIds = content.match(idPattern) || [];
  node.referenced_ids = [...new Set(foundIds)].map((id) => cleanText(id)); // Deduplicate and clean

  return node;
}

function weaveConnections(nodes) {
  console.log(`\n🕸️  Weaving Connections...`);
  const links = [];

  nodes.forEach((sourceNode) => {
    if (sourceNode.referenced_ids) {
      sourceNode.referenced_ids.forEach((targetId) => {
        // Find target
        const targetNode = nodes.find((n) => n.id === targetId);
        if (targetNode && targetNode.id !== sourceNode.id) {
          // Create Link
          links.push({
            source: sourceNode.id,
            target: targetNode.id,
            relation: "REFERENCES",
            weight: 0.5,
            description: `Auto-detected reference in ${sourceNode.label}`,
          });
        }
      });
    }
  });

  return links;
}

function generatePRS() {
  console.log(`\n🔮 INITIATING GENESIS PROTOCOL...`);
  console.log(`📂 Scanning Target: ${CONFIG.rootDir}`);

  const files = scanDirectory(CONFIG.rootDir);
  console.log(`📄 Found ${files.length} potential artifacts.`);

  let cognitive_loom = {
    nodes: [],
    links: [], // Auto-linking logic could go here in v2.0
  };

  let registry = {
    UMBs: [],
    AOPs: [],
    GUCAs: [],
    SELTS: [],
    Others: [],
  };

  // --- PROCESSING LOOP ---
  files.forEach((file) => {
    const node = extractMetadata(file);

    // Only include if it looks like a valid artifact (has an ID or specific type)
    if (node.id.startsWith("UNKNOWN") && !node.label.includes("PRS")) {
      // Optional: Skip files that have no metadata headers
      return;
    }

    console.log(`   [+] Ingested: ${node.id} (${node.label})`);

    // Add to Nodes
    cognitive_loom.nodes.push(node);

    // Sort into Registry
    const registryEntry = {
      id: node.id,
      status: "Active",
      path: node.location,
    };
    if (node.id.startsWith("UMB")) registry.UMBs.push(registryEntry);
    else if (node.id.startsWith("AOP")) registry.AOPs.push(registryEntry);
    else if (node.id.startsWith("GUCA")) registry.GUCAs.push(registryEntry);
    else if (node.id.startsWith("SELT")) registry.SELTS.push(registryEntry);
    else registry.Others.push(registryEntry);
  });

  // --- LINKING PHASE (The Weaver) ---
  // --- LINKING PHASE (The Weaver) ---
  cognitive_loom.links = weaveConnections(cognitive_loom.nodes);

  // --- ASSEMBLY ---
  const finalJSON = {
    ...CONFIG.prsHeader,
    cognitive_loom,
    registry,
    omni_log_summary: {
      total_nodes: cognitive_loom.nodes.length,
      last_generated: new Date().toISOString(),
    },
  };

  // --- WRITING THE GRIMOIRE ---
  fs.writeFileSync(CONFIG.outputFile, JSON.stringify(finalJSON, null, 2));

  console.log(
    `\n✨ SUCCESS: The Grimoire (${CONFIG.outputFile}) has been rewritten.`,
  );
  console.log(`🔗 Total Nodes Linked: ${cognitive_loom.nodes.length}`);
  console.log(`🛡️ System is Online.`);
}

// --- EXECUTE ---
generatePRS();
