from dataclasses import dataclass, field
from typing import Any, Dict, Type


@dataclass
class DeltaPacket:
    """Strict DAMP mutation payload generated by system execution."""

    mutations: Dict[Type, Dict[int, Any]] = field(default_factory=dict)
    structural_migrations: Dict[str, Any] = field(default_factory=dict)

    def merge(self, other: "DeltaPacket") -> None:
        """Deterministically merges another delta packet into this packet."""
        for comp_type, updates in other.mutations.items():
            if comp_type not in self.mutations:
                self.mutations[comp_type] = {}
            self.mutations[comp_type].update(updates)

        for key, val in other.structural_migrations.items():
            self.structural_migrations[key] = val

