"""| Key               | Value                          | Description       |
| :---------------- | :----------------------------- | :---------------- |
| **Artifact ID**   | `TOOL-GENERATE-BARRELS-001`                | The Sovereign ID. |
| **Official Name** | `generate_barrels.py`                   | The Filename.     |
| **Version**       | **v13.1**                      | The Standard.     |
| **Domain**        | `GVRN`                         | The Subject.      |
| **Evolution**     | **Autonomous Vigil**           | The Alignment.    |
| **Status (State)**| `[CANONIZED]`                  | The Lifecycle.    |
| **Celestial Class**| `[PLANET]`                    | The Tier.         |
| **Relations**     | `GOVERNED_BY: CORE-CODEX-001`  | The Network.      |
| **Integrity Hash**| `[AUTO-GENERATED]`             | Verification.     |
| **Genesis Stamp** | `2026-02-23`                       | Creation Date.    |.
"""

import datetime
import json
import os
import re
import sys
from pathlib import Path

if sys.platform == "win32":
    try:
        import io

        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
    except Exception:
        pass

# --- CONFIGURATION ---
CONFIG = {
    "scanDirs": ["./_governance", "./axion-core/src", "./axion-core/.agent"],
    "outputFile": "./axion-core/storage/PRS-001.json",
    "allowedExtensions": [".md", ".txt"],
    "prsHeader": {
        "artifact_id": "PRS-001",
        "official_name": "The Phoenix Rosetta Stone (Axion Core)",
        "version": "5.0 (Live-Generated)",
        "governing_ethos": "Guardian of Truth",
        "description": "The Master Navigational Hub and Knowledge Graph for Axion Core, auto-generated by the Transmutation Architect.",
    },
}

# --- REGEX PATTERNS ---
PATTERNS = {
    "id": re.compile(
        r"(?:(?:\*\*|#+\s*)?(?:Artifact ID|Module ID|Blueprint ID|Playbook ID|Command ID|Metric ID|Log ID)(?:\*\*)?):\s*(.*)",
        re.IGNORECASE,
    ),
    "name": re.compile(
        r"(?:(?:\*\*|#+\s*)?(?:Official Name|Module Name|Blueprint Title|Playbook Title|Command Title|Metric Title|Log Title)(?:\*\*)?):\s*(.*)",
        re.IGNORECASE,
    ),
    "type": re.compile(r"(?:(?:\*\*|#+\s*)?(?:Artifact Type|Type)(?:\*\*)?):\s*(.*)", re.IGNORECASE),
    "domain": re.compile(
        r"(?:(?:\*\*|#+\s*)?(?:Primary Domain Alignment|Primary Domain|Domain)(?:\*\*)?):\s*(.*)",
        re.IGNORECASE,
    ),
    "ethos": re.compile(r"(?:(?:\*\*|#+\s*)?(?:Governing Ethos)(?:\*\*)?):\s*(.*)", re.IGNORECASE),
    "purpose": re.compile(
        r"(?:(?:\*\*|#+\s*)?(?:Core Purpose|Purpose|Objective|What \(.*\))(?:\*\*)?):\s*(.*)",
        re.IGNORECASE,
    ),
    "tags": re.compile(r"(?:(?:\*\*|#+\s*)?(?:Semantic Tags|Tags)(?:\*\*)?):\s*(.*)", re.IGNORECASE),
    "refs": re.compile(r"(?:UMB|AOP|GUCA|SELT|DOC|gw)-[A-Z]{2,}-\d{3}|AISTF|OGLN|Synarche|Phoenix_Cycle|ContextWeave"),
}


def clean_text(text: str) -> str:
    if not text:
        return ""
    # Remove leading/trailing markdown bold/italic/headers and invisible spaces
    text = re.sub(r"^[\s*#_]+|[\s*#_]+$", "", text.strip())
    return text


def extract_metadata(file_path):
    try:
        with open(file_path, encoding="utf-8", errors="ignore") as f:
            content = f.read()
    except Exception as e:
        print(f"Error reading {file_path}: {e}")
        return None

    filename = os.path.basename(file_path)
    node = {
        "id": "UNKNOWN-" + filename,
        "label": filename,
        "type": "Artifact",
        "definition": "No definition found.",
        "tags": [],
        "location": str(file_path).replace("\\", "/"),
    }

    # 1. Extract ID
    match = PATTERNS["id"].search(content)
    if match:
        node["id"] = clean_text(match.group(1))

    # 2. Extract Name
    match = PATTERNS["name"].search(content)
    if match:
        node["label"] = clean_text(match.group(1))

    # 3. Extract Type
    match = PATTERNS["type"].search(content)
    if match:
        node["type"] = clean_text(match.group(1))
    elif node["id"].startswith("UMB"):
        node["type"] = "Blueprint"
    elif node["id"].startswith("AOP"):
        node["type"] = "Protocol"
    elif node["id"].startswith("GUCA"):
        node["type"] = "Command"
    elif node["id"].startswith("SELT"):
        node["type"] = "Log"

    # 4. Extract Definition
    match = PATTERNS["purpose"].search(content)
    if match:
        clean_def = match.group(1).strip().replace("Summary: ", "")
        if len(clean_def) > 300:
            clean_def = clean_def[:297] + "..."
        node["definition"] = clean_text(clean_def)

    # 5. Extract Tags/Domain
    match = PATTERNS["domain"].search(content)
    if match:
        node["tags"].append(clean_text(match.group(1)))

    match = PATTERNS["tags"].search(content)
    if match:
        raw_tags = re.split(r",|#", match.group(1))
        for t in raw_tags:
            clean = clean_text(t)
            if clean and clean not in node["tags"]:
                node["tags"].append(clean)

    # 6. Extract References
    found_ids = PATTERNS["refs"].findall(content)
    node["referenced_ids"] = list(set(found_ids))

    return node


def generate_barrels():
    print("\n[INIT] INITIATING GENESIS PROTOCOL (AXION CORE - PYTHON)...")

    nodes = []
    registry = {"UMBs": [], "AOPs": [], "GUCAs": [], "SELTS": [], "Others": []}

    for scan_dir in CONFIG["scanDirs"]:
        print(f"📂 Scanning Target: {scan_dir}")
        base_path = Path(scan_dir)
        if not base_path.exists():
            print(f"   [WARNING] Directory not found: {scan_dir}")
            continue

        for file_path in base_path.rglob("*"):
            if file_path.suffix in CONFIG["allowedExtensions"]:
                node = extract_metadata(file_path)
                if not node:
                    continue

                # Skip files with no metadata unless they are PRS
                if node["id"].startswith("UNKNOWN") and "PRS" not in node["label"]:
                    continue

                print(f"   [+] Ingested: {node['id']} ({node['label']})")
                nodes.append(node)

                # Sort into Registry
                entry = {"id": node["id"], "status": "Active", "path": node["location"]}
                if node["id"].startswith("UMB"):
                    registry["UMBs"].append(entry)
                elif node["id"].startswith("AOP"):
                    registry["AOPs"].append(entry)
                elif node["id"].startswith("GUCA"):
                    registry["GUCAs"].append(entry)
                elif node["id"].startswith("SELT"):
                    registry["SELTS"].append(entry)
                else:
                    registry["Others"].append(entry)

    # Linking Phase
    print("\n🕸️  Weaving Connections...")
    links = []
    node_ids = {n["id"] for n in nodes}
    for source_node in nodes:
        for target_id in source_node.get("referenced_ids", []):
            if target_id in node_ids and target_id != source_node["id"]:
                links.append(
                    {
                        "source": source_node["id"],
                        "target": target_id,
                        "relation": "REFERENCES",
                        "weight": 0.5,
                        "description": f"Auto-detected reference in {source_node['label']}",
                    }
                )

    # Assembly
    final_output = {
        **CONFIG["prsHeader"],
        "last_updated": datetime.datetime.now().isoformat(),
        "cognitive_loom": {"nodes": nodes, "links": links},
        "registry": registry,
        "omni_log_summary": {
            "total_nodes": len(nodes),
            "last_generated": datetime.datetime.now().isoformat(),
        },
    }

    # Ensure output directory exists
    output_path = Path(CONFIG["outputFile"])
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(final_output, f, indent=2)

    print(f"\n[SUCCESS] The Grimoire ({CONFIG['outputFile']}) has been rewritten.")
    print(f"Total Nodes Linked: {len(nodes)}")
    print("System is Online.")


if __name__ == "__main__":
    generate_barrels()
