name: Biome Quality Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  quality:
    name: Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Run Biome CI
        run: biome ci .
